-- Write your own SQL object definition here, and it'll be included in your package.
-- Insert sample data for 151 electoral divisions
INSERT INTO [dbo].[ElectoralDivision] ([division_name], [current_mp_name], [current_mp_party], [total_registered_voters])
VALUES 
('Adelaide', 'Steve Georganas', 'Australian Labor Party', 113245),
('Aston', 'Mary Doyle', 'Australian Labor Party', 108765),
('Ballarat', 'Catherine King', 'Australian Labor Party', 114532),
('Banks', 'David Coleman', 'Liberal Party of Australia', 106789),
('Barker', 'Tony Pasin', 'Liberal Party of Australia', 116543),
('Barton', 'Linda Burney', 'Australian Labor Party', 109876),
('Bass', 'Bridget Archer', 'Liberal Party of Australia', 103456),
('Bean', 'David Smith', 'Australian Labor Party', 105678),
('Bendigo', 'Lisa Chesters', 'Australian Labor Party', 112345),
('Bennelong', 'Jerome Laxale', 'Australian Labor Party', 108765),
('Berowra', 'Julian Leeser', 'Liberal Party of Australia', 110987),
('Blair', 'Shayne Neumann', 'Australian Labor Party', 107654),
('Blaxland', 'Jason Clare', 'Australian Labor Party', 104321),
('Bonner', 'Ross Vasta', 'Liberal National Party of Queensland', 109876),
('Boothby', 'Louise Miller-Frost', 'Australian Labor Party', 111234),
('Bowman', 'Henry Pike', 'Liberal National Party of Queensland', 108765),
('Braddon', 'Gavin Pearce', 'Liberal Party of Australia', 102345),
('Bradfield', 'Paul Fletcher', 'Liberal Party of Australia', 114567),
('Brand', 'Madeleine King', 'Australian Labor Party', 110987),
('Brisbane', 'Stephen Bates', 'Australian Greens', 106543),
('Bruce', 'Julian Hill', 'Australian Labor Party', 108765),
('Burt', 'Matt Keogh', 'Australian Labor Party', 113456),
('Calare', 'Andrew Gee', 'Independent', 109876),
('Calwell', 'Maria Vamvakinou', 'Australian Labor Party', 112345),
('Canberra', 'Alicia Payne', 'Australian Labor Party', 115678),
('Canning', 'Andrew Hastie', 'Liberal Party of Australia', 108765),
('Capricornia', 'Michelle Landry', 'Liberal National Party of Queensland', 110987),
('Casey', 'Aaron Violi', 'Liberal Party of Australia', 107654),
('Chifley', 'Ed Husic', 'Australian Labor Party', 106543),
('Chisholm', 'Carina Garland', 'Australian Labor Party', 109876),
('Clark', 'Andrew Wilkie', 'Independent', 103456),
('Cook', 'Scott Morrison', 'Liberal Party of Australia', 112345),
('Cooper', 'Ged Kearney', 'Australian Labor Party', 115678),
('Corangamite', 'Libby Coker', 'Australian Labor Party', 110987),
('Corio', 'Richard Marles', 'Australian Labor Party', 108765),
('Cowan', 'Anne Aly', 'Australian Labor Party', 111234),
('Cowper', 'Pat Conaghan', 'National Party of Australia', 106543),
('Cunningham', 'Alison Byrnes', 'Australian Labor Party', 109876),
('Curtin', 'Kate Chaney', 'Independent', 114567),
('Dawson', 'Andrew Willcox', 'Liberal National Party of Queensland', 108765),
('Deakin', 'Michael Sukkar', 'Liberal Party of Australia', 110987),
('Dickson', 'Peter Dutton', 'Liberal National Party of Queensland', 112345),
('Dobell', 'Emma McBride', 'Australian Labor Party', 107654),
('Dunkley', 'Peta Murphy', 'Australian Labor Party', 109876),
('Durack', 'Melissa Price', 'Liberal Party of Australia', 103456),
('Eden-Monaro', 'Kristy McBain', 'Australian Labor Party', 108765),
('Fadden', 'Stuart Robert', 'Liberal National Party of Queensland', 111234),
('Fairfax', 'Ted O''Brien', 'Liberal National Party of Queensland', 110987),
('Farrer', 'Sussan Ley', 'Liberal Party of Australia', 106543),
('Fenner', 'Andrew Leigh', 'Australian Labor Party', 109876),
('Fisher', 'Andrew Wallace', 'Liberal National Party of Queensland', 108765),
('Flinders', 'Zoe McKenzie', 'Liberal Party of Australia', 112345),
('Flynn', 'Colin Boyce', 'Liberal National Party of Queensland', 107654),
('Forde', 'Bert van Manen', 'Liberal National Party of Queensland', 110987),
('Forrest', 'Nola Marino', 'Liberal Party of Australia', 109876),
('Fowler', 'Dai Le', 'Independent', 106543),
('Franklin', 'Julie Collins', 'Australian Labor Party', 103456),
('Fraser', 'Daniel Mulino', 'Australian Labor Party', 112345),
('Fremantle', 'Josh Wilson', 'Australian Labor Party', 110987),
('Gellibrand', 'Tim Watts', 'Australian Labor Party', 108765),
('Gilmore', 'Fiona Phillips', 'Australian Labor Party', 106543),
('Gippsland', 'Darren Chester', 'National Party of Australia', 109876),
('Goldstein', 'Zoe Daniel', 'Independent', 114567),
('Gorton', 'Brendan O''Connor', 'Australian Labor Party', 112345),
('Grayndler', 'Anthony Albanese', 'Australian Labor Party', 115678),
('Greenway', 'Michelle Rowland', 'Australian Labor Party', 110987),
('Grey', 'Rowan Ramsey', 'Liberal Party of Australia', 107654),
('Griffith', 'Max Chandler-Mather', 'Australian Greens', 109876),
('Groom', 'Garth Hamilton', 'Liberal National Party of Queensland', 108765),
('Hasluck', 'Tania Lawrence', 'Australian Labor Party', 106543),
('Hawke', 'Sam Rae', 'Australian Labor Party', 111234),
('Herbert', 'Phillip Thompson', 'Liberal National Party of Queensland', 108765),
('Higgins', 'Michelle Ananda-Rajah', 'Australian Labor Party', 114567),
('Hindmarsh', 'Mark Butler', 'Australian Labor Party', 110987),
('Hinkler', 'Keith Pitt', 'Liberal National Party of Queensland', 107654),
('Holt', 'Cassandra Fernando', 'Australian Labor Party', 112345),
('Hotham', 'Clare O''Neil', 'Australian Labor Party', 109876),
('Hughes', 'Jenny Ware', 'Liberal Party of Australia', 108765),
('Hume', 'Angus Taylor', 'Liberal Party of Australia', 110987),
('Hunter', 'Dan Repacholi', 'Australian Labor Party', 106543),
('Indi', 'Helen Haines', 'Independent', 109876),
('Isaacs', 'Mark Dreyfus', 'Australian Labor Party', 112345),
('Jagajaga', 'Kate Thwaites', 'Australian Labor Party', 110987),
('Kennedy', 'Bob Katter', 'Katter''s Australian Party', 103456),
('Kingsford Smith', 'Matt Thistlethwaite', 'Australian Labor Party', 111234),
('Kingston', 'Amanda Rishworth', 'Australian Labor Party', 109876),
('Kooyong', 'Monique Ryan', 'Independent', 114567),
('La Trobe', 'Jason Wood', 'Liberal Party of Australia', 110987),
('Lalor', 'Joanne Ryan', 'Australian Labor Party', 112345),
('Leichhardt', 'Warren Entsch', 'Liberal National Party of Queensland', 107654),
('Lilley', 'Anika Wells', 'Australian Labor Party', 109876),
('Lindsay', 'Melissa McIntosh', 'Liberal Party of Australia', 108765),
('Lingiari', 'Marion Scrymgour', 'Australian Labor Party', 101234),
('Longman', 'Terry Young', 'Liberal National Party of Queensland', 110987),
('Lyne', 'David Gillespie', 'National Party of Australia', 106543),
('Lyons', 'Brian Mitchell', 'Australian Labor Party', 103456),
('Macarthur', 'Mike Freelander', 'Australian Labor Party', 109876),
('Mackellar', 'Sophie Scamps', 'Independent', 112345),
('Macnamara', 'Josh Burns', 'Australian Labor Party', 114567),
('Macquarie', 'Susan Templeman', 'Australian Labor Party', 108765),
('Makin', 'Tony Zappia', 'Australian Labor Party', 110987),
('Mallee', 'Anne Webster', 'National Party of Australia', 106543),
('Maranoa', 'David Littleproud', 'Liberal National Party of Queensland', 103456),
('Maribyrnong', 'Bill Shorten', 'Australian Labor Party', 111234),
('Mayo', 'Rebekha Sharkie', 'Centre Alliance', 109876),
('McEwen', 'Rob Mitchell', 'Australian Labor Party', 112345),
('McMahon', 'Chris Bowen', 'Australian Labor Party', 110987),
('McPherson', 'Karen Andrews', 'Liberal National Party of Queensland', 108765),
('Melbourne', 'Adam Bandt', 'Australian Greens', 115678),
('Menzies', 'Keith Wolahan', 'Liberal Party of Australia', 110987),
('Mitchell', 'Jerome Laxale', 'Australian Labor Party', 112345),
('Monash', 'Russell Broadbent', 'Liberal Party of Australia', 108765),
('Moncrieff', 'Angie Bell', 'Liberal National Party of Queensland', 110987),
('Moore', 'Ian Goodenough', 'Liberal Party of Australia', 109876),
('Moreton', 'Graham Perrett', 'Australian Labor Party', 108765),
('New England', 'Barnaby Joyce', 'National Party of Australia', 106543),
('Newcastle', 'Sharon Claydon', 'Australian Labor Party', 110987),
('Nicholls', 'Sam Birrell', 'National Party of Australia', 107654),
('North Sydney', 'Kylea Tink', 'Independent', 114567),
('O''Connor', 'Rick Wilson', 'Liberal Party of Australia', 103456),
('Oxley', 'Milton Dick', 'Australian Labor Party', 110987),
('Page', 'Kevin Hogan', 'National Party of Australia', 108765),
('Parkes', 'Mark Coulton', 'National Party of Australia', 106543),
('Parramatta', 'Andrew Charlton', 'Australian Labor Party', 112345),
('Paterson', 'Meryl Swanson', 'Australian Labor Party', 109876),
('Pearce', 'Tracey Roberts', 'Australian Labor Party', 110987),
('Perth', 'Patrick Gorman', 'Australian Labor Party', 112345),
('Petrie', 'Luke Howarth', 'Liberal National Party of Queensland', 108765),
('Rankin', 'Jim Chalmers', 'Australian Labor Party', 110987),
('Reid', 'Sally Sitou', 'Australian Labor Party', 112345),
('Richmond', 'Justine Elliot', 'Australian Labor Party', 108765),
('Riverina', 'Michael McCormack', 'National Party of Australia', 106543),
('Robertson', 'Gordon Reid', 'Australian Labor Party', 109876),
('Ryan', 'Elizabeth Watson-Brown', 'Australian Greens', 112345),
('Scullin', 'Andrew Giles', 'Australian Labor Party', 110987),
('Shortland', 'Pat Conroy', 'Australian Labor Party', 108765),
('Solomon', 'Luke Gosling', 'Australian Labor Party', 101234),
('Spence', 'Matt Burnell', 'Australian Labor Party', 109876),
('Sturt', 'James Stevens', 'Liberal Party of Australia', 112345),
('Swan', 'Zaneta Mascarenhas', 'Australian Labor Party', 110987),
('Sydney', 'Tanya Plibersek', 'Australian Labor Party', 115678),
('Tangney', 'Sam Lim', 'Australian Labor Party', 110987),
('Wannon', 'Dan Tehan', 'Liberal Party of Australia', 106543),
('Warringah', 'Zali Steggall', 'Independent', 114567),
('Watson', 'Tony Burke', 'Australian Labor Party', 110987),
('Wentworth', 'Allegra Spender', 'Independent', 114567),
('Werriwa', 'Anne Stanley', 'Australian Labor Party', 109876),
('Whitlam', 'Stephen Jones', 'Australian Labor Party', 108765),
('Wide Bay', 'Llew O''Brien', 'Liberal National Party of Queensland', 107654),
('Wills', 'Peter Khalil', 'Australian Labor Party', 112345),
('Wright', 'Scott Buchholz', 'Liberal National Party of Queensland', 108765);